-- Identidad y tenancy

CREATE TABLE tenant (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(100) NOT NULL,
    subscription_type VARCHAR(20)  NOT NULL DEFAULT 'FREE',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_tenant_subscription
        CHECK (subscription_type IN ('FREE', 'PRO', 'ENTERPRISE'))
);

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL REFERENCES tenant (id),
    email         VARCHAR(160) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(120) NOT NULL,
    disabled_at   TIMESTAMPTZ,
    tenant_role   VARCHAR(16)  NOT NULL DEFAULT 'MEMBER',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_app_user_email     UNIQUE (email),
    CONSTRAINT uq_app_user_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT ck_app_user_tenant_role
        CHECK (tenant_role IN ('TENANT_ADMIN', 'MEMBER'))
);
CREATE INDEX idx_app_user_tenant ON app_user (tenant_id);

CREATE TABLE refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    jti         VARCHAR(36)  NOT NULL,
    issued_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked_at  TIMESTAMPTZ,
    CONSTRAINT uq_refresh_token_jti UNIQUE (jti)
);
CREATE INDEX idx_refresh_token_user ON refresh_token (user_id);

-- Workflow y delivery

CREATE TABLE workflow_definition (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id              BIGINT       NOT NULL REFERENCES tenant (id),
    name                   VARCHAR(100) NOT NULL,
    is_builtin_template    BOOLEAN      NOT NULL DEFAULT FALSE,
    states_and_transitions JSONB        NOT NULL,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_workflow_definition_id_tenant   UNIQUE (id, tenant_id),
    CONSTRAINT uq_workflow_definition_tenant_name UNIQUE (tenant_id, name)
);
CREATE INDEX idx_workflow_definition_tenant ON workflow_definition (tenant_id);

CREATE TABLE project (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id              BIGINT       NOT NULL REFERENCES tenant (id),
    name                   VARCHAR(100) NOT NULL,
    description            TEXT,
    workflow_definition_id BIGINT       NOT NULL,
    status                 VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_project_workflow
        FOREIGN KEY (workflow_definition_id, tenant_id)
        REFERENCES workflow_definition (id, tenant_id),
    CONSTRAINT uq_project_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT ck_project_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);
CREATE INDEX idx_project_tenant ON project (tenant_id);

CREATE TABLE project_membership (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT      NOT NULL REFERENCES project (id)  ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    role        VARCHAR(16) NOT NULL,
    scrum_label VARCHAR(16),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_membership_role
        CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER')),
    CONSTRAINT ck_membership_scrum_label
        CHECK (scrum_label IS NULL
               OR scrum_label IN ('PRODUCT_OWNER', 'SCRUM_MASTER', 'DEVELOPER')),
    CONSTRAINT uq_membership_project_user UNIQUE (project_id, user_id)
);
CREATE INDEX idx_membership_project ON project_membership (project_id);
CREATE INDEX idx_membership_user    ON project_membership (user_id);

CREATE TABLE board (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT       NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_board_project ON board (project_id);

CREATE TABLE work_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT       NOT NULL,
    project_id          BIGINT       NOT NULL,
    parent_work_item_id BIGINT       REFERENCES work_item (id) ON DELETE SET NULL,
    sprint_work_item_id BIGINT       REFERENCES work_item (id) ON DELETE SET NULL,
    type                VARCHAR(32)  NOT NULL,
    state               VARCHAR(32)  NOT NULL,
    title               VARCHAR(255) NOT NULL,
    description         TEXT,
    business_value      INTEGER,
    urgency             INTEGER,
    story_points        INTEGER,
    assignee_id         BIGINT       REFERENCES app_user (id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_work_item_project
        FOREIGN KEY (project_id, tenant_id)
        REFERENCES project (id, tenant_id) ON DELETE CASCADE,
    CONSTRAINT ck_work_item_not_self_parent
        CHECK (parent_work_item_id IS NULL OR parent_work_item_id <> id),
    CONSTRAINT ck_work_item_not_self_sprint
        CHECK (sprint_work_item_id IS NULL OR sprint_work_item_id <> id),
    CONSTRAINT ck_work_item_business_value
        CHECK (business_value IS NULL OR business_value BETWEEN 0 AND 100),
    CONSTRAINT ck_work_item_urgency
        CHECK (urgency IS NULL OR urgency BETWEEN 0 AND 100),
    CONSTRAINT ck_work_item_story_points
        CHECK (story_points IS NULL OR story_points >= 0)
);
CREATE INDEX idx_work_item_tenant        ON work_item (tenant_id);
CREATE INDEX idx_work_item_project_state ON work_item (project_id, state);
CREATE INDEX idx_work_item_parent        ON work_item (parent_work_item_id);
CREATE INDEX idx_work_item_sprint        ON work_item (sprint_work_item_id);
CREATE INDEX idx_work_item_assignee      ON work_item (assignee_id);

-- Colaboración

CREATE TABLE comment (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_item_id BIGINT      NOT NULL REFERENCES work_item (id) ON DELETE CASCADE,
    author_id    BIGINT      NOT NULL REFERENCES app_user (id),
    body         TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_comment_work_item ON comment (work_item_id);
CREATE INDEX idx_comment_author    ON comment (author_id);

-- Fuera de los tres bounded contexts (formulario público de contacto)

CREATE TABLE contact (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    email      VARCHAR(160) NOT NULL,
    message    TEXT         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
